services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    ports:
      - "3000:3000"
      - "9229:9229" # for debugging
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
      - turbo_cache:/app/.turbo/cache
      - pnpm_store:/pnpm/store
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=chat_app
      - DB_USER=root
      - DB_PASSWORD=password
      - JWT_SECRET=dev-secret-key
      - PORT=3000
      - TURBO_TELEMETRY_DISABLED=1
      - PNPM_VERSION=8.6.0
    depends_on:
      - mysql
    working_dir: /app/apps/backend
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    # Expose the frontend port directly
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./packages:/app/packages
      - turbo_cache:/app/.turbo/cache
      - pnpm_store:/pnpm/store
    environment:
      - NODE_ENV=development
      # Point to Nginx for WebSocket connections that need HTTP/3
      - VITE_API_URL=https://localhost:5002
      - VITE_WS_URL=wss://localhost:5002
      - TURBO_TELEMETRY_DISABLED=1
      - PNPM_VERSION=8.6.0
    depends_on:
      - backend
    working_dir: /app/apps/frontend
    restart: unless-stopped

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "5002:5002/tcp"   # Custom HTTPS port for API and WebSockets
      - "5003:5003/udp"   # Required for HTTP/3 (QUIC)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    # Enable HTTP/3 in Nginx
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.core.somaxconn=4096
      - net.ipv4.ip_local_port_range=1024 65000

  mysql:
    image: mysql/mysql-server:8.0
    platform: linux/amd64
    ports:
      - "12321:3306"
    environment:
      - MYSQL_DATABASE=chat_app
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
  
volumes:
  mysql_data:
  backend_node_modules:
  turbo_cache:
  pnpm_store:
  migration_cache: 