FROM node:22-alpine

WORKDIR /app

# Install PNPM
RUN corepack enable && corepack prepare pnpm@8.6.0 --activate

# Install dependencies
COPY . .

# Install dependencies
RUN pnpm install

# Set the working directory to the frontend app
WORKDIR /app/apps/frontend

# Expose the port the app runs on
EXPOSE 5173

# Start the app in development mode
CMD ["pnpm", "run", "dev"] 
