FROM node:22-alpine

# Set pnpm version according to packageManager in package.json
ENV PNPM_VERSION=8.6.0

# Install pnpm with exact version
RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate

# Set working directory
WORKDIR /app


# Copy the rest of the application
COPY . .

RUN pnpm install

# Set working directory to backend
WORKDIR /app/apps/backend

# Turborepo cache setup
ENV TURBO_TELEMETRY_DISABLED=1
ENV TURBO_CACHE_DIR=/app/.turbo/cache

# Expose ports
EXPOSE 3000
EXPOSE 9229

CMD ["pnpm", "start:dev"] 
